
# TODO: add elixir container

db:
  image: postgres:9.4
  env_file: .env
  ports:
    - "5432:5432"
  volumes:
    # ugly hack to avoid symlinks on windows partition
    - /tmp/db/data:/var/lib/postgresql/data
