
nginx:
  image: nginx:1.9.2
  ports:
    - "80:80"
  volumes:
    - "./data/files:/files"
    - "./config/nginx:/etc/nginx/conf.d"
  links:
    - "web"

web:
  image: trenpixster/elixir:1.0.5
  command: "mix do deps.get, compile, phoenix.server"
  working_dir: "/web"
  env_file: .env
  ports:
    - "4000:4000"
  volumes:
    - "./web:/web"
    - "./data/files:/files"
  links:
    - "db"

db:
  image: postgres:9.4
  env_file: .env
  ports:
    - "5432:5432"
  volumes:
    # TODO: add entry for import/export dir
    - "./data/db:/var/lib/postgresql/data"


